# Tells the web server to run on port 8080
server.port=8080

# We provide the DB credentials here too, just in case Spring Boot 
# needs to initialize any background web security features later
spring.datasource.url=jdbc:mysql://localhost:3306/university_ms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sajal@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver